# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 642b2725431a8333e233bc8a5bb32f0c7f4170f0681257e663a5f5bdc9b886fe433e39db1018ab3cd9506db553ab600a234ddecb100fd54933d46a94656b69bc

test:
  secret_key_base: 045b40ff8db26cae9762721a56ec2f3bd17a780a30912c3517951367f4879e845d23e2251a68914303be51b00ca004ed90a807ee42dd5373cb04511e9a782c0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: fdfa9daf6c57265c83aac624a006680c48ab1522f476cab90e2356e0cb419e4cb37578678c383c458afe132bbfca0e58973360c2b9db8f9a475b5e086789b47c
